"""Add user payment methods table

Revision ID: 57c6bfe540d2
Revises: a8d509755a27
Create Date: 2025-08-19 20:51:50.791407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57c6bfe540d2'
down_revision = 'a8d509755a27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_history', sa.Column('payment_method_id', sa.Integer(), nullable=True))
    op.add_column('payment_history', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('payment_history', sa.Column('failure_reason', sa.String(length=500), nullable=True))
    op.add_column('payment_history', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('payment_history', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'payment_history', 'user_payment_methods', ['payment_method_id'], ['id'], ondelete='SET NULL')
    op.drop_column('payment_history', 'payment_method')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_history', sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payment_history', type_='foreignkey')
    op.drop_column('payment_history', 'updated_at')
    op.drop_column('payment_history', 'metadata')
    op.drop_column('payment_history', 'failure_reason')
    op.drop_column('payment_history', 'description')
    op.drop_column('payment_history', 'payment_method_id')
    # ### end Alembic commands ###
