"""Create invoices table

Revision ID: 7ea7d82aa472
Revises: 57c6bfe540d2
Create Date: 2025-08-20 00:17:09.211088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea7d82aa472'
down_revision = '57c6bfe540d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
