"""Add ANALYZING step to StepName enum

Revision ID: f6d536f952fb
Revises: 92b399a09d56
Create Date: 2025-08-28 20:00:35.710489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d536f952fb'
down_revision = '92b399a09d56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add ANALYZING to StepName enum
    op.execute("ALTER TYPE stepname ADD VALUE 'ANALYZING' AFTER 'SEGMENTING'")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'generate_subtitles',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('jobs', 'generate_dubbing',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_jobs_user_job_number'), 'jobs', ['user_job_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_user_job_number'), table_name='jobs')
    op.alter_column('jobs', 'generate_dubbing',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('jobs', 'generate_subtitles',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###
